### ISSUE TITLE
Android Bootloader Interface 

### ISSUE THREAD

**Issue by Celestin8139** [log1cs/Auto-Script-Unlock845LG#4]
When I try to install fastboot a message appears written " the hash of the file is not present in the specified catalog file. The file is probably corrupted or has been tampered with"

**Comment by log1cs** [comment]
Can you be more speciic about it?

**Comment by Celestin8139** [comment]
When I go to install the fastboot drivers comes an error message saying that it was not possible to install the drivers because the hash is missing
