### ISSUE TITLE
LMG710TM

### ISSUE THREAD

**Issue by phodina** [log1cs/Auto-Script-Unlock845LG#5]
Hello @log1cs ,
do you know what's the issue with the T-Mobile variant?

I imagine the SDM845 EDL binaries are the same for the phones. The issue might be with the signature of the binary.

If you state that the T-Mobile variant is unsupported does it mean that the certificates/public keys burned in the chip fuses do not come from LG Electronics but from T-Mobile?

**Comment by log1cs** [comment]
Well, as far as I know, the T-Mobile version of G7 uses different revision of the Snapdragon 845 than the rest of the G7s. So yeah, it will fails (immediately i guess?) if you try to load it in QFIL.

Still, the Velvet 4G use the same revision of the 845 like those damn G7s.

**Comment by phodina** [comment]
Hm, interesting could you share the screen of the HW Info for the SoC?
Here's the LG G7 Thinq T-Mobile version.

![lmg710_soc](https://github.com/log1cs/Unlock845/assets/2997905/c8fe6384-6eb4-456d-aae4-e416d950758b)

And here's my second phone Sony XZ2

![akari_soc](https://github.com/log1cs/Unlock845/assets/2997905/422bb793-7954-4bc1-946b-2c9c9ab3c096)

They appear to be the same revision. Do you know if the firehose elf file needs to be signed by the Qualcomm or the vendor?

**Comment by phodina** [comment]
Also do you know if the LGUP tool allows to crossflash the device?

I might try this approach in order to unlock the bootloader.

**Comment by log1cs** [comment]
You cannot crossflash, nor unlock the bootloader if you had a G710TM.

**Comment by phodina** [comment]
I can get the UFS desoldered and dumped. This could give us access to the bootloader and the mechanism it uses to verify the oem code.

Perhaps static analysis in Ghidra or dynamic in QEMU might be able to help with the cracking of the unlock.bin code.

Do you think it's a way to consider?

**Comment by log1cs** [comment]
Eh... That's not possible though, the unlock.bin usually generated by the server, maybe some sort of algorithm (i don't really know, because my device is unlocked unofficially)

However, I heard that LG Server uses some sort of algorithm to generate the unlock key.

Give this a check:
https://forum.xda-developers.com/t/lg-bootloader-unlock-code-cracking-the-algorithm.4339959/

**Comment by log1cs** [comment]
Closing the issue.
